@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
content-type: application/json

{
    "name": "Daniel2",
    "email": "daniel3@mail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
content-type: application/json

{
    "email": "daniel3@mail.com",
    "password": "123456"
}

###

POST {{baseUrl}}/questions
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Operator de coalescência nula em JS 2122",
    "content": "Qual o operador de coalescência nula em js 11?"
}

###
GET {{baseUrl}}/questions?page=1
content-type: application/json
Authorization: Bearer {{authToken}}

###